### ISSUE TITLE
intarlace\proressive swither?

### ISSUE THREAD

**Issue by Iga44** [kFYatek/tweakvec#1]
Hello!)

Is it possible to switch between interlace and progressive mode during running retropie by means tweakvec?
( Yeah, i know, that i could each time pull off sd card, plug it to pc, edit config.cfg from sdtvmode=0 to 16. After that run tweakvec again)

I've not totally understood what mean as 4 article of your manual : " 

 

> If_ you are using custom scripts (e.g. runcommand-onstart.sh) that invoke tvservice, you will need to repeat the above command after each such call.
> 
> Example set of commands for switching to progressive PAL60:
> 
> tvservice -c "NTSC 4:3 P"; sudo python3 /home/pi/tweakvec/tweakvec.py --preset PAL60; fbset -depth 8; fbset -depth 32; tvservice _-s

>

cause i don't use any scripts or runcommand at all
 
  And what do those parameters fbset -depth 8; fbset -depth 32; tvservice _-s  are mean?

**Comment by kFYatek** [comment]
Hi,

I might add options to switch modes later, but please note that switching between progressive and interlaced modes is possible using `tvservice`:

* To switch to 480i (interlaced mode): `sudo tvservice -c "NTSC 4:3"`
* To switch to 240p (progressive mode): `sudo tvservice -c "NTSC 4:3 P"`

Please note that the screen may go blank after doing that. It can usually be restored by switching back and forth between virtual terminals (Alt+F2, then Alt+F1, or programmatically: `sudo chvt 2; sudo chvt 1`).

You can run `tweakvec` afterwards to change colour encoding from NTSC to PAL60 or whatever you need, or put all commands on the same line, e.g.:
```
sudo tvservice -c "NTSC 4:3 P"; sudo chvt 2; sudo chvt 1; sudo python3 /home/pi/tweakvec/tweakvec.py --preset PAL60
```
Does that resolve your issue?

**Comment by Iga44** [comment]
Yes.
But, unfortunately, it blocked all my personal setups picture position on the tv screen by pasting "#" everywhere in config.cfg. And no one game can be running after command
`sudo tvservice -c "NTSC 4:3 P"; sudo chvt 2; sudo chvt 1; sudo python3 /home/pi/tweakvec.py --preset PAL60`
it's exit back to retropie after launching

But I mean as "switch" is maybe some item in retropie menu or hotkey but not each time close emulationstation and enter the command or get pc and run this command thru the terminal by ssh

**Comment by kFYatek** [comment]
Sorry, I don't have that level of familiarity with RetroPie. I think you should ask on RetroPie support forums or something like that.

**Comment by Iga44** [comment]
Ok, one more question at the same time - does tweakves can be used in recalbox?

**Comment by kFYatek** [comment]
`tweakvec` will run on any Linux-based OS on any Raspberry Pi that has a composite output (though I only tested it with a Pi 3B and 4B), provided that there is a reasonably recent kernel and Python interpreter available.

I'm not familiar with Recalbox - quickly looking at its image, it looks like it's Linux-based, but there is no Python 3 installed by default. So I'm pretty sure that platform would need some modding before running `tweakvec` is possible. And I have no idea how to configure it to do so.

**Comment by Iga44** [comment]
Ok, thanks alot!)
