### ISSUE TITLE
recalbox 9.0 tweakvec problem

### ISSUE THREAD

**Issue by Iga44** [kFYatek/tweakvec#3]
Hello man! 

Could I bother you once again?

I've used tweacvec in recalbox long time before the new version has released.
But now at recalbox 9.0 when i write in terminal "python3 tweakvec.py --preset PAL60 "
I've get message:

**DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
import distutils.util**
![image](https://user-images.githubusercontent.com/76435104/228201769-197153df-342a-428d-9b5c-b7e9d812f701.png)

not really understand what it's mean about....
So, could you tell me what i need to do to make it work again?
( I've asked it in recalbox's forum but don't get answer about it)
Thnx.

**Comment by 03stevensmi** [comment]
I'm getting this error on a raspberry pi 5 using LibreELEC:
`python tweakvec.py --preset NTSC-J
/storage/tweakvec.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util
[Errno 2] No such file or directory: '/sys/firmware/devicetree/base/__symbols__/pixelvalve2'
Are you running on a Raspberry Pi?
`

Any help?

**Comment by kFYatek** [comment]
Hi @Iga44 and @03stevensmi

I removed the use of the `distutils` package and fixed the VideoCore version detection routine. This should work now in your cases. However I don't have a Raspberry Pi 5 to test it there.

Also I'd like to bring your attention to the fact that support for all TV norms supported by the Pi, including NTSC-J and PAL60, has been in the kernel (both mainline and Raspberry Pi Foundation's fork) for quite a while, so you might consider stopping the use of `tweakvec` and migrating to KMS instead. See the [`enable_tvout` section in the config.txt docs](https://www.raspberrypi.com/documentation/computers/config_txt.html#enable_tvout) for details.

**Comment by Iga44** [comment]
No, I'm user just....And i've use raspberry pi 4  and tweakvec with retropie or recalbox.  Maybe it's incompatible with LibreELEC at all.Anyway, you should ask comrade kFYatek from github https://github.com/kFYatek , cause he is author01.02.2024, 01:32, "03stevensmi" ***@***.***>:
I'm getting this error on a raspberry pi 5 using LibreELEC:
python tweakvec.py --preset NTSC-J /storage/tweakvec.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives import distutils.util [Errno 2] No such file or directory: '/sys/firmware/devicetree/base/__symbols__/pixelvalve2' Are you running on a Raspberry Pi? 
Any help?

**Comment by Iga44** [comment]
Does raspberry pi 5 has composite vide output??01.02.2024, 02:32, "kFYatek" ***@***.***>:
Hi @Iga44 and @03stevensmi
I removed the use of the distutils package and fixed the VideoCore version detection routine. This should work now in your cases. However I don't have a Raspberry Pi 5 to test it there.
Also I'd like to bring your attention to the fact that support for all TV norms supported by the Pi, including NTSC-J and PAL60, has been in the kernel (both mainline and Raspberry Pi Foundation's fork) for quite a while, so you might consider stopping the use of tweakvec and migrating to KMS instead. See the enable_tvout section in the config.txt docs for details.

**Comment by kFYatek** [comment]
@Iga44 

> Does raspberry pi 5 has composite vide output??

It does, but it's in a form of unpopulated pads on the PCB, so you'll need to solder your own output jack or cable to connect it to a TV.

There's also no analog _audio_ output of any kind, so you'll need to add one through either a hat or a USB DAC.

**Comment by 03stevensmi** [comment]
@kFYatek @Iga44 I can confirm I'm using composite.
Libreelec latest works with rpi 3b+ but the rpi5 is now giving me this error message
But also when just using the command
python3 tweakvec.py. No --preset. At least I could get the help to load up 3 days prior to the latest tweakvec changes.
It was just the --presets giving me the pixel2 error before.

But now This is what I get on the pi5:
`python tweakvec.py
Traceback (most recent call last):
  File "/storage/tweakvec.py", line 867, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/storage/tweakvec.py", line 831, in _main
    current_config = ctx().current_config()
                     ^^^^^
  File "/storage/tweakvec.py", line 823, in ctx
    ctx_value = TweakVecContext()
                ^^^^^^^^^^^^^^^^^
  File "/storage/tweakvec.py", line 405, in __init__
    self.vec = VecAccessor(self.memfd, self.mapper, self.pv.model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/tweakvec.py", line 159, in __init__
    super().__init__(memfd, mapper.map_symbol_address('vec'))
  File "/storage/tweakvec.py", line 105, in __init__
    self.memory = mmap.mmap(memfd, length=length, offset=address)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
`

**Comment by 03stevensmi** [comment]
@kFYatek I have now tried it on multiple option systems such as the latest raspian and recalbox!
They all throw me the error mentioned above even when just running the command by itself:
`python3 tweakvec.py`

As I mentioned before, I could get the help to show up before the latest changes but as of now I get that same error message no matter what. 

@kFYatek could you please take a look at this?

**Comment by kFYatek** [comment]
> At least I could get the help to load up 3 days prior to the latest tweakvec changes.

`python3 tweakvec.py --help` should still work without errors. If you run the program without arguments, it tries to read the current settings, which is why it's failing.

Anyway, the original problem with the deprecation warning has been solved, so I'm closing this issue. Discussion about the Pi5 issue will be continued in #5.

**Comment by Iga44** [comment]
What a different in usage between tweakvec.py --preset PAL60     and   vc4.tv_norm=pal60 in /boot/firmware/cmdline.txt    ???08.02.2024, 00:22, "kFYatek" ***@***.***>:

At least I could get the help to load up 3 days prior to the latest tweakvec changes.

python3 tweakvec.py --help should still work without errors. If you run the program without arguments, it tries to read the current settings, which is why it's failing.
Anyway, the original problem with the deprecation warning has been solved, so I'm closing this issue. Discussion about the Pi5 issue will be continued in #5.

**Comment by kFYatek** [comment]
> What a different in usage between tweakvec.py --preset PAL60     and   vc4.tv_norm=pal60 in /boot/firmware/cmdline.txt

@Iga44 Please note that the `tv_norm` values are case-sensitive, so you need to set `vc4.tv_norm=PAL60`. There should be no difference in the output compared to setting it via `tweakvec` - the difference is that the mode is set natively by the kernel instead of using an external tool.
