### ISSUE TITLE
[Errno 2] No such file or directory: '/sys/firmware/devicetree/bas e/__symbols__/pixelvalve2'

### ISSUE THREAD

**Issue by 03stevensmi** [kFYatek/tweakvec#4]
Hey,
I'm getting this error on a raspberry pi 5 using LibreELEC:
`python tweakvec.py --preset NTSC-J
/storage/tweakvec.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util
[Errno 2] No such file or directory: '/sys/firmware/devicetree/base/__symbols__/pixelvalve2'
Are you running on a Raspberry Pi?
`

Im on the latest version of LibreELEC using composite out on the Raspberry pi 5.
I can confirm this works on the same (latest version) of LibreELEC on the RaspberryPI 3b+
And on the latest version of osmc on the RaspberryPI 3b+.

Can also confirm the same error message on [Alastor27] Fork of TweakVEC.

So this looks like a RaspberryPI 5 Issue!
Any help?

@Alastor27
@kFYatek 
Any of you guys could look into this please?

**Comment by kFYatek** [comment]
Issues with these specific error messages have been solved in #3.

The script still doesn't work on Pi5, due to a separate issue reported as #5. I'm closing this issue; please continue in #5 with regard to making `tweakvec` work on Pi5 in general.
